tasks:
  - init: >
      gp sync-done prep &&
      pip install -r requirements.txt
  - name: Serve MkDocsÅ
    init: gp sync-wait prep
    command: >
      echo "Starting MkDocs server..." &&
      mkdocs serve --dev-addr 0.0.0.0:8000

ports:
  - port: 8000
    onOpen: open-preview
